spring:
  application:
    name: gw
  data:
    mongodb:
      username: social
      password: social123456789
      host: localhost
      port: 27017
      database: social-media
      auto-index-creation: true